version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: docker_auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #Servicio para simular el servicio de correo
  mailpit:
    image: axllent/mailpit:latest
    container_name: docker_mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:


  
